### ISSUE TITLE
Using mqtt-gpio without Ks3

### ISSUE THREAD

**Issue by SgtErnestBilko** [sourcesimian/mqtt-gpio#2]
Hi
I would like to use your docker container but I do not use Ks3.  I have 2 Pi4's running on a home automation system using relays to open and close stuff.  I control through Node-Red but the node seems to have a bug which means NodeRed has to be restarted every 3 deployments.  It is open source but I am not clever enough to find the bug and recode.

I would like to use your docker as it seems a much more modular and contained way of setiiing up my system   Is it possible to make a docker-compose.yml to interact with your container?  i.e. open ports, set up volumes for persistance (probably making available on the host and most importantly using a user defined config.yaml?  Could I impose on your time to give me some pointers ?

I am sorry if these are silly questions but as I say I have no knowledge of Ks3.

Thank you

**Comment by SgtErnestBilko** [comment]
I am content you delete this issue and applogise for raising it.  The anwser is (I think) use the two files in "Docker" to make your own container using your own configuration.   yes ?

**Comment by sourcesimian** [comment]
Hi SgtErnestBilko

There is no specific requirement on K3S, it is just what I use. Any container run time should work, and keep in mind that mqtt-gpio can also run directly on the host. I just prefer containerisation. The mqtt-gpio container on [DockerHub](https://hub.docker.com/r/sourcesimian/mqtt-gpio) will work in docker.

To launch mqtt-gpio in docker the command line would be something like:
```
docker run -it --rm -v ${PWD}/mqtt-gpio-config.yaml -v /sys --privileged sourcesimian/mqtt-gpio:0.0.2-armv6 /mqtt-gpio-config.yaml
```
where your config file is named `mqtt-gpio-config.yaml`. Converting this to a docker compose file would be about the same.

Note that you will need to mount the `/sys` directory and additionally allow "privileged" system access to allow mqtt-gpio to interact with GPIO device files.

I hope this helps

**Comment by SgtErnestBilko** [comment]
You are kind, I will try that, thank you for your help

On 12 Jan 2023, at 09:03, Source Simian ***@***.******@***.***>> wrote:



Hi SgtErnestBilko

There is no specific requirement on K3S, it is just what I use. Any container run time should work, and keep in mind that mqtt-gpio can also run directly on the host. I just prefer containerisation. The mqtt-gpio container on DockerHub<https://hub.docker.com/r/sourcesimian/mqtt-gpio> will work in docker.

To launch mqtt-gpio in docker the command line would be something like:

docker run -it --rm -v ${PWD}/mqtt-gpio-config.yaml -v /sys --privileged sourcesimian/mqtt-gpio:0.0.2-armv6 /mqtt-gpio-config.yaml


where your config file is named mqtt-gpio-config.yaml. Converting this to a docker compose file would be about the same.

Note that you will need to mount the /sys directory and additionally allow "privileged" system access to allow mqtt-gpio to interact with GPIO device files.

I hope this helps

**Comment by SgtErnestBilko** [comment]
I appreciate I am being a pain in the ****, but I hope you can help.

The run command you kindly set out loads "config-demo.yaml"  rather than my mqtt-gpio-config.yaml (in the directory in which docker runs.)

The same for my docker-compose.yml file

version: "3.5"
services:
  gpiomqqt:
    container_name: gpiomqtt
    image: sourcesimian/mqtt-gpio:0.0.2-armv6
    command: /mqtt-gpio-config.yaml
    privileged: true
    volumes:
      - '${PWD}/mqtt-gpio-config.yaml'
      - /sys

**Comment by sourcesimian** [comment]
A docker compose file like this should work:
```
version: '3.5'

services:
  mqtt-gpio:
    image: sourcesimian/mqtt-gpio:0.0.2-armv6
    entrypoint: [mqtt-gpio, /mqtt-gpio-config.yaml]
    volumes:
    - /sys:/sys
    - ./mqtt-gpio-config.yaml:/mqtt-gpio-config.yaml
    privileged: true
```

**Comment by SgtErnestBilko** [comment]
Thank you once again.  You beat me by 20 minutes.  I got a docker-compose to work but not in the way you intended.  It overwrote config.yaml inside the docker.

For anyone else "landing" here.......I can confirm that your docker-compose file executes without error on a Pi3 running Debian Bullseye 32bit Lite.  It also successfully sends and receives MQTT data.  I havn't tested the pins yet but I am not anticipating any issues. 

Thank you for the work you put into creating this solution and thank you very much for providing an alternative implementation.

**Comment by sourcesimian** [comment]
Overwriting `config.yaml` inside the container is a good way since `mqtt-gpio` expects that file by default. The longer version just makes things a but more obvious.

You're most welcome, and I'm glad you find mqtt-gpio useful. good luck with your home automation. I have added a Docker section to the docs (currently on dev branch).

**Comment by SgtErnestBilko** [comment]
Firstly I must apologise for being lazy !!

If the answer isn’t easy please tell me to …….stop bothering you and “do your own research”

If there a way I can get my pi (using mqtt-gpio in a docker) to publish all the gpio states to the mqtt broker on command.

I have my own website (with a nodered back end) which controls / reports on equipment in an astronomy dome.  The webpage has buttons (red and green) which switch on and off relays on a pi.  On bringing up the webpage I want to be sure the button colours (i.e. relay states) are correct  before I’m able to toggle buttons.   I hope that makes sense.

Thank you

Ian

**Comment by SgtErnestBilko** [comment]
Please ignore the email below
